version: '3'

services:
  pgsql:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - './pg_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    shm_size: 1g

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - pgsql
    ports:
      - 8080:8080

volumes:
  pg_data:
    driver: local